export const typeInfo = {
  context: { label: '背景', color: '#8f88ad', icon: 'Layers' },
  decision: { label: '决策', color: '#c69365', icon: 'GitBranch' },
  skill: { label: '方法', color: '#6a9c99', icon: 'Sparkles' },
  task: { label: '任务', color: '#9683b4', icon: 'CheckSquare' },
  preference: { label: '偏好', color: '#ba8591', icon: 'Heart' },
  emotion: { label: '情绪', color: '#b4788a', icon: 'Heart' },
  time: { label: '时序', color: '#7f96ab', icon: 'Clock' },
};

export const collections = [
  { id: 'product', name: '产品与灵感', color: '#c9957d', icon: 'Lightbulb' },
  { id: 'coding', name: '构建与代码', color: '#9a90b9', icon: 'Code2' },
  { id: 'research', name: '阅读与研究', color: '#7fa3a4', icon: 'BookOpen' },
  { id: 'life', name: '生活与日常', color: '#a6ab80', icon: 'Leaf' },
];

export const initialMemories = [
  {
    id: 'mem-01',
    title: '让 AI 记住我，而不只是对话',
    summary: '一个独立于工具的记忆层。让背景、偏好与做过的决定，在下一次对话里自然延续。',
    content: '核心想法\n让记忆跟着人走。换一个 AI，也不用再介绍一遍自己。\n\n一次教会，处处理解\n我希望 AI 记住的不只是“说过什么”，更是我为什么这样做。偏好、决策和经验，应当成为可以持续积累的个人上下文。\n\n关于我：偏好与工作方式，不必重复解释。\n关于正在做的事：项目与决策来路，随时接着往下走。\n带到每个 AI：一次沉淀，多端复用，积累始终属于自己。\n\n设计时，我在意的三件事\n01 先看见内容，再看见工具。让记录和阅读保持轻松，把复杂的配置收进需要时才出现的地方。\n02 每段记忆，都有来处。保留来源、关联和时间，让 AI 的理解可以被追溯和修正。\n03 记忆属于我，也由我决定去向。按上下文选择连接范围，随时查看、编辑与导出。',
    type: 'context', collection: 'product', tags: ['respire', '产品愿景', '跨工具记忆'], source: '手动记录',
    createdAt: '2026-09-06T09:10:00+08:00', updatedAt: '2026-09-06T10:42:00+08:00', timeLabel: '10:42',
    pinned: true, parentId: null, relatedIds: ['mem-02', 'mem-03', 'mem-10'],
  },
  {
    id: 'mem-02',
    title: '好的界面，应该给内容让路',
    summary: '低对比背景、浮动面板与清晰的文字层级；用克制的暖色强调下一步。',
    content: '这次桌面体验采用接近纸张的浅灰底色。内容面板用轻微的明暗和柔和投影区分，不依赖密集的边框来分割空间。\n\n颜色承担明确的功能：暖杏色用于当前关注与主要动作，其他分类颜色只作为轻量提示。状态不仅靠颜色表达，还要有文字或图标，让信息更容易理解。\n\nMac 上的常用路径要足够短：Command + K 搜索，Command + N 新建，Escape 关闭浮层。搜索结果可以直接进入记忆，阅读时始终保留返回路径。\n\n阅读区减少装饰，正文保持舒适行长。重要信息通过标题、段落和少量标签自然浮现，不把每一块内容都做成醒目的卡片。',
    type: 'decision', collection: 'product', tags: ['界面设计', 'Mac 优先', '阅读体验'], source: 'Claude Code',
    createdAt: '2026-09-06T08:30:00+08:00', updatedAt: '2026-09-06T10:18:00+08:00', timeLabel: '10:18',
    pinned: true, parentId: null, relatedIds: ['mem-01', 'mem-03', 'mem-15'],
  },
  {
    id: 'mem-03',
    title: '我的协作偏好：先行动，再讲清楚',
    summary: '中文沟通，直接说结论；可逆的小事自行推进，关键取舍保留理由。',
    content: '默认用中文沟通，保留常用技术名词的英文写法。先说结论和下一步，再补充必要的依据，避免长篇铺垫。\n\n对已经明确的需求，优先完成可逆的工作。遇到影响范围较大的取舍时，说明选项与后果，再确认方向。不要对同一个已授权动作反复询问。\n\n代码交付要包含实际变更、验证结果和仍然存在的限制。设计交付要可以打开、点击和比较，而不只是描述一张理想中的界面。\n\n记忆里的偏好是协作的起点，不应该覆盖当次明确提出的新要求。需求发生变化时，先遵循新的上下文，再更新这条记忆。',
    type: 'preference', collection: 'product', tags: ['协作方式', '中文', '交付标准'], source: '手动记录',
    createdAt: '2026-09-03T14:05:00+08:00', updatedAt: '2026-09-06T09:56:00+08:00', timeLabel: '09:56',
    pinned: true, parentId: null, relatedIds: ['mem-01', 'mem-02'],
  },
  {
    id: 'mem-04',
    title: '编程练习平台 · 九月迭代',
    summary: '整理题库、校验答案与改进提交体验，将大任务拆成能够独立验收的小步骤。',
    content: '九月迭代围绕练习平台的内容质量与提交体验展开。将题目整理、答案校验和界面反馈分开推进，避免一次改动涉及过多未知因素。\n\n本轮题库工作先处理基础题，再处理组合题。每一批都保留原题、解析和校验记录，便于发现问题后追溯到具体输入。\n\n任务树分成项目、专题与执行项三级。父任务保存目标和验收方式，子任务记录具体进展，完成后的结论再回写到相关记忆。\n\n最终验收关注三件事：题目显示完整，判题结果可解释，提交失败后能够恢复。',
    type: 'task', collection: 'coding', tags: ['题库', '九月计划', '任务树'], source: 'Codex',
    createdAt: '2026-09-01T10:00:00+08:00', updatedAt: '2026-09-06T09:30:00+08:00', timeLabel: '09:30',
    pinned: false, parentId: null, relatedIds: ['mem-05', 'mem-06', 'mem-07'],
  },
  {
    id: 'mem-05',
    title: '基础题专题 · 答案与解析校验',
    summary: '逐题检查选项、答案与解析是否一致，边界输入单独记录。',
    content: '这一专题是九月题库迭代的一个子任务。先统一题目字段，再逐题比对选项、答案与解析，最后检查页面上的展示效果。\n\n校验过程中，不凭记忆修改答案。能够运行的代码通过执行结果核实；需要推导的题目保留简短推理，便于后续复查。\n\n发现空数组、重复值、整型上界等边界场景时，将它们加入单独的检查清单。不要只确认常见输入能够通过。\n\n本次执行项是完成第 313 与 314 组练习的上线前检查。',
    type: 'task', collection: 'coding', tags: ['基础题', '答案校验', '边界输入'], source: 'Codex',
    createdAt: '2026-09-04T13:20:00+08:00', updatedAt: '2026-09-06T09:20:00+08:00', timeLabel: '09:20',
    pinned: false, parentId: 'mem-04', relatedIds: ['mem-04', 'mem-06', 'mem-08'],
  },
  {
    id: 'mem-06',
    title: '第 313 / 314 组练习上线检查',
    summary: '答案复核完成；下一步检查长标题换行与重复提交反馈。',
    content: '第 313 与 314 组练习已完成题干、选项和答案复核。将检查结果保存到本条执行记忆，作为专题任务下的最后一级。\n\n本次发现两处容易遗漏的细节：长题干在窄窗口下出现不自然换行，连续点击提交时缺少处理中反馈。两项都已经加入发布检查清单。\n\n上线前需要再走一次真实使用路径：打开练习、选择答案、提交、查看解析、返回列表。每一步都应有清楚的状态，保留用户之前的选择。\n\n完成后更新父任务的进度，并将可以复用的经验独立整理成方法记忆。',
    type: 'task', collection: 'coding', tags: ['发布检查', '交互反馈', '进行中'], source: 'Codex',
    createdAt: '2026-09-05T15:30:00+08:00', updatedAt: '2026-09-06T09:12:00+08:00', timeLabel: '09:12',
    pinned: false, parentId: 'mem-05', relatedIds: ['mem-04', 'mem-05', 'mem-07'],
  },
  {
    id: 'mem-07',
    title: '编译问题排查：从最小复现开始',
    summary: '先保存报错现场，再缩小输入；每次只改变一个条件。',
    content: '遇到编译或运行异常时，先保留完整报错、触发命令与相关环境信息。不要连续修改多个地方后再尝试判断哪一步生效。\n\n把问题缩小到能稳定触发的最小示例。移除与报错无关的代码，使用固定输入，并检查依赖版本与实际执行目录。\n\n对于浮点输出，区分计算精度与展示精度。需要固定小数位时明确使用 fixed 与 setprecision，并检查输出约定。\n\n修复后先运行最小示例，再验证原始场景。把根因和必要条件写进记忆，避免只留下一个没有上下文的解决命令。',
    type: 'skill', collection: 'coding', tags: ['调试', '最小复现', 'C++'], source: 'Claude Code',
    createdAt: '2026-09-02T16:15:00+08:00', updatedAt: '2026-09-05T18:24:00+08:00', timeLabel: '昨天',
    pinned: false, parentId: null, relatedIds: ['mem-06', 'mem-08'],
  },
  {
    id: 'mem-08',
    title: '二分查找：先写清区间约定',
    summary: '左闭右开与左右闭合都可用，关键是让更新规则与退出条件保持一致。',
    content: '实现二分查找之前，先用一句话写清楚搜索区间的含义。区间约定确定后，循环条件、边界更新和返回位置都应由同一套规则推导。\n\n使用左闭右开区间时，右边界可以等于数组长度。查找首个满足条件的位置，需要保证每次更新都让区间严格缩小。\n\n对空数组、单元素、全部满足、全部不满足与重复值分别检查。不要用只包含不同元素的常规示例证明正确性。\n\n在代码评审里，优先解释不变式，再逐行查看实现。清楚的不变式通常比背诵模板更容易发现边界问题。',
    type: 'skill', collection: 'coding', tags: ['算法', '二分查找', '边界条件'], source: 'Codex',
    createdAt: '2026-09-03T11:45:00+08:00', updatedAt: '2026-09-05T16:08:00+08:00', timeLabel: '昨天',
    pinned: false, parentId: null, relatedIds: ['mem-05', 'mem-07'],
  },
  {
    id: 'mem-09',
    title: '阅读笔记：让信息产生连接',
    summary: '读完后留下自己的问题、可复用的观点，以及它与现有工作的关系。',
    content: '阅读的目标不是积累更多摘抄，而是让新的信息能够参与之后的思考。每次阅读结束，至少写下一条自己的理解。\n\n一条有用的笔记包含来源、核心观点和适用条件。对于作者的结论，要区分直接证据、推论和个人评价，不把它们混在一起。\n\n整理笔记时，寻找它与已有问题的连接。例如关于信息检索的文章，可以关联到 respire 的搜索体验；关于认知负荷的研究，可以帮助解释界面上的取舍。\n\n没有想清楚的地方也值得留下。一个准确的问题，比一段看起来完整但未经消化的摘要更有用。',
    type: 'skill', collection: 'research', tags: ['阅读方法', '知识连接', '笔记'], source: '手动记录',
    createdAt: '2026-09-02T20:00:00+08:00', updatedAt: '2026-09-05T14:32:00+08:00', timeLabel: '昨天',
    pinned: false, parentId: null, relatedIds: ['mem-10', 'mem-14'],
  },
  {
    id: 'mem-10',
    title: '记忆质量，比记忆数量更重要',
    summary: '可理解、可追溯、可更新，是一条好记忆的三个标准。',
    content: '记忆库的价值不由记录总数决定。真正有用的记忆，应该能够被正确找到，并在合适的上下文里帮助行动。\n\n第一是可理解：脱离原始聊天后仍然知道它在说什么。避免只保存“这样就可以了”，需要补上对象、条件和结果。\n\n第二是可追溯：知道内容来自哪里、什么时候形成、为什么值得保留。第三是可更新：偏好改变、项目结束或经验失效时，能够修订，而不是无限叠加相互矛盾的记录。\n\n整理时优先合并重复表述，保留关键差异。存在冲突的记忆先展示时间与来源，再由用户决定哪条应当继续生效。',
    type: 'decision', collection: 'product', tags: ['记忆质量', '可追溯', '整理'], source: 'Claude Code',
    createdAt: '2026-09-01T15:00:00+08:00', updatedAt: '2026-09-04T17:12:00+08:00', timeLabel: '周五',
    pinned: true, parentId: null, relatedIds: ['mem-01', 'mem-09', 'mem-16'],
  },
  {
    id: 'mem-11',
    title: '周末散步路线：沿河走一段',
    summary: '喜欢安静、有树荫、能随时停下来的路线；散步时只记录灵感关键词。',
    content: '周末散步更喜欢沿河或公园里的连续步道。路线不需要太长，能够在有树荫的地方慢慢走，途中有可以坐下来的地方就很好。\n\n比起赶景点，更看重轻松的节奏。出门前只确认天气和返回方式，不把半天安排得太满。\n\n散步中出现灵感时，先记几个关键词，回家后再整理成完整记忆。尽量让记录服务于体验，而不是把注意力一直留在屏幕里。',
    type: 'preference', collection: 'life', tags: ['散步', '周末', '慢一点'], source: '手动记录',
    createdAt: '2026-09-04T19:10:00+08:00', updatedAt: '2026-09-04T19:10:00+08:00', timeLabel: '周五',
    pinned: false, parentId: null, relatedIds: ['mem-12', 'mem-13'],
  },
  {
    id: 'mem-12',
    title: '给深度工作留出一段完整时间',
    summary: '上午优先处理需要思考的工作，沟通与整理集中在下午。',
    content: '需要持续思考的设计、写作和问题排查，尽量安排在上午。开始前写下这一段时间希望完成的具体结果，减少临时切换。\n\n不要求整天保持高强度专注。把沟通、资料整理与零散维护集中处理，给复杂问题留下完整的时间段。\n\n结束时用几句话记录当前进度、未解决的问题和下一步。第二天继续工作时，可以直接从这些线索恢复上下文。\n\n如果计划被打断，优先缩小当次目标，完成一个有意义的部分。把工作恢复得更容易，也是一种效率。',
    type: 'preference', collection: 'life', tags: ['工作节奏', '专注', '上下文恢复'], source: '手动记录',
    createdAt: '2026-09-01T08:45:00+08:00', updatedAt: '2026-09-04T11:25:00+08:00', timeLabel: '周五',
    pinned: false, parentId: null, relatedIds: ['mem-03', 'mem-11'],
  },
  {
    id: 'mem-13',
    title: '九月的小清单',
    summary: '整理桌面，读完一本书，给每周留一个没有安排的下午。',
    content: '九月想把日常安排得轻一点。先整理一次桌面与下载文件夹，让常用的东西更容易找到。\n\n阅读只保留一本正在读的书。每周记下一条真正产生影响的观点，允许阅读进度自然发生。\n\n每周留一个没有安排的下午，可以散步、去咖啡馆，也可以什么都不做。这份清单用于提醒自己，不作为必须完成的考核。',
    type: 'task', collection: 'life', tags: ['九月', '生活清单', '留白'], source: '手动记录',
    createdAt: '2026-09-01T21:00:00+08:00', updatedAt: '2026-09-03T20:05:00+08:00', timeLabel: '周四',
    pinned: false, parentId: null, relatedIds: ['mem-11', 'mem-12'],
  },
  {
    id: 'mem-14',
    title: '研究方向：个人记忆如何被找回',
    summary: '从关键词、语义与时间三个入口，观察人们如何重新找到一段经历。',
    content: '个人记忆的检索常常从模糊线索开始。人们可能只记得讨论过的话题、使用的工具，或者大概发生的时间，而不记得原来的标题。\n\n探索三个互补入口：关键词适合明确对象，语义描述适合模糊意图，时间和项目适合逐步缩小范围。设计上可以将它们组合，但不要要求用户先理解检索机制。\n\n结果中展示一段能够解释“为什么匹配”的摘要，并保留来源和时间。用户应该能快速判断是否找到了需要的记忆。\n\n后续验证重点是实际找回任务的完成率与耗时。本条属于研究假设，尚不能当作已经证明的结论。',
    type: 'context', collection: 'research', tags: ['信息检索', '研究假设', '语义搜索'], source: '浏览器',
    createdAt: '2026-09-02T13:30:00+08:00', updatedAt: '2026-09-03T15:40:00+08:00', timeLabel: '周四',
    pinned: false, parentId: null, relatedIds: ['mem-01', 'mem-09', 'mem-10'],
  },
  {
    id: 'mem-15',
    title: '快捷键应该帮助人保持思路',
    summary: '搜索、新建与关闭优先覆盖；在界面中展示快捷键，让使用习惯自然形成。',
    content: '桌面应用的快捷键从最常用的三条路径开始：搜索记忆、新建记忆、关闭当前浮层。每个快捷键都应该与可见的界面动作对应。\n\nCommand + K 打开搜索，输入后即可看到结果。Command + N 打开新建窗口，并把焦点放在第一个输入框。Escape 逐层关闭当前浮层，返回原来的阅读位置。\n\n编辑内容时保留正常的文本操作，不抢占输入控件的常用按键。快捷键提示放在按钮或菜单旁边，不依赖单独的说明页。\n\n验证时要同时检查鼠标和键盘路径。一个动作是否轻松，取决于从当前状态到结果的完整过程。',
    type: 'decision', collection: 'product', tags: ['快捷键', 'Mac', '效率'], source: 'Claude Code',
    createdAt: '2026-09-02T11:00:00+08:00', updatedAt: '2026-09-02T16:42:00+08:00', timeLabel: '周三',
    pinned: false, parentId: null, relatedIds: ['mem-02', 'mem-03'],
  },
  {
    id: 'mem-16',
    title: '工具连接：让记忆在合适的范围内流动',
    summary: '每个工具可以单独连接，并选择全部记忆或仅当前项目。',
    content: '不同工具承担不同工作，所需的上下文也不同。工具连接页应该清楚展示每个连接的状态，以及它可以使用的记忆范围。\n\n日常协作工具可以选择全部记忆；针对单个代码项目的工具，可以限定为仅当前项目。范围选择应当随时可见，也能够被修改。\n\n连接与断开都需要明确反馈。断开连接意味着停止向该工具提供新的记忆，不应让用户猜测当前状态。\n\n原有的注入管理能力以更容易理解的“工具连接”呈现。底层接入细节可以保留在详情中，主要界面先回答连接到了哪里、是否正常、能够使用什么。',
    type: 'context', collection: 'product', tags: ['工具连接', '记忆范围', '跨工具'], source: '手动记录',
    createdAt: '2026-09-01T12:30:00+08:00', updatedAt: '2026-09-02T10:16:00+08:00', timeLabel: '周三',
    pinned: false, parentId: null, relatedIds: ['mem-01', 'mem-10'],
  },
];

export const initialConnections = [
  { id: 'claude', name: 'Claude Code', description: '让每一次构建，都从理解你开始。', icon: 'claude', connected: true, scope: '全部记忆' },
  { id: 'codex', name: 'Codex', description: '保留项目背景，延续代码中的思路。', icon: 'codex', connected: true, scope: '仅当前项目' },
  { id: 'cursor', name: 'Cursor', description: '让编辑器知道你的习惯与决定。', icon: 'cursor', connected: true, scope: '仅当前项目' },
  { id: 'opencode', name: 'OpenCode', description: '在终端里，也能接上之前的工作。', icon: 'opencode', connected: false, scope: '仅当前项目' },
  { id: 'chatgpt', name: 'ChatGPT', description: '把熟悉的上下文，带进新的对话。', icon: 'chatgpt', connected: false, scope: '全部记忆' },
  { id: 'dsh', name: 'DSH', description: '连接你的工作流，复用已积累的记忆。', icon: 'terminal', connected: false, scope: '全部记忆' },
];

export const suggestedQuestions = [
  '我对 AI 协作有哪些偏好？',
  'respire 的设计方向是什么？',
  '九月编程项目进行到哪了？',
];
